mayflower_oci8_test_homepage:
    pattern:  /
    defaults: { _controller: MayflowerOci8TestBundle:Default:index }

mayflower_oci8_test_image:
    pattern:  /image/{id}
    defaults: { _controller: MayflowerOci8TestBundle:Default:image }