<?php

namespace Mayflower\Oci8TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends EntityRepository
{

    /**
     * @return mixed
     */
    public function getMaxId()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select($qb->expr()->max('a.id'))
            ->from(Asset::NAME, 'a');

        $result = $qb->getQuery()->getScalarResult();

        return $result[0][1];
    }
}
